frr defaults traditional
hostname upstream-a
service integrated-vtysh-config
!
interface lo
 ip address 10.10.255.1/32
 ipv6 address 3fff:10::1/128
!
interface eth1
 description to r1 (customer AS 65001)
 ip address 100.64.11.1/30
 ipv6 address 3fff:10:0:11::1/64
!
interface eth2
 description peering with upstream-b (AS 65020)
 ip address 100.64.12.1/30
 ipv6 address 3fff:10:0:12::1/64
!
interface eth3
 description to transit (AS 65030)
 ip address 100.64.13.1/30
 ipv6 address 3fff:30:0:13::1/64
!
interface eth4
 description internal LAN (cross-traffic host)
 ip address 10.10.10.1/24
 ipv6 address 3fff:10:10::1/64
!
interface eth5
 description IXP port
 ip address 100.64.99.10/24
 ipv6 address 3fff:ff::10/64
!
ip route 10.10.0.0/16 Null0
ipv6 route 3fff:10::/32 Null0
!
bgp as-path access-list OWN-CUST seq 5 permit ^$
bgp as-path access-list OWN-CUST seq 10 permit ^65001$
!
router bgp 65010
 bgp router-id 10.10.255.1
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 no bgp default ipv4-unicast
 neighbor 100.64.11.2 remote-as 65001
 neighbor 3fff:10:0:11::2 remote-as 65001
 neighbor 100.64.12.2 remote-as 65020
 neighbor 3fff:10:0:12::2 remote-as 65020
 neighbor 100.64.13.2 remote-as 65030
 neighbor 3fff:30:0:13::2 remote-as 65030
 neighbor 100.64.99.1 remote-as 65100
 neighbor 3fff:ff::1 remote-as 65100
 !
 address-family ipv4 unicast
  network 10.10.0.0/16
  neighbor 100.64.11.2 activate
  neighbor 100.64.12.2 activate
  neighbor 100.64.12.2 route-map TO-PEER out
  neighbor 100.64.13.2 activate
  neighbor 100.64.13.2 route-map TO-PEER out
  neighbor 100.64.99.1 activate
  neighbor 100.64.99.1 route-map TO-PEER out
 exit-address-family
 !
 address-family ipv6 unicast
  network 3fff:10::/32
  neighbor 3fff:10:0:11::2 activate
  neighbor 3fff:10:0:12::2 activate
  neighbor 3fff:10:0:12::2 route-map TO-PEER out
  neighbor 3fff:30:0:13::2 activate
  neighbor 3fff:30:0:13::2 route-map TO-PEER out
  neighbor 3fff:ff::1 activate
  neighbor 3fff:ff::1 route-map TO-PEER out
 exit-address-family
!
route-map TO-PEER permit 10
 match as-path OWN-CUST
!
