frr defaults traditional
hostname dest-2
service integrated-vtysh-config
!
interface lo
 ip address 10.50.255.1/32
 ipv6 address 3fff:50::1/128
!
interface eth1
 description destination LAN (target2)
 ip address 10.50.10.1/24
 ipv6 address 3fff:50:10::1/64
!
interface eth2
 description IXP port (primary path)
 ip address 100.64.99.50/24
 ipv6 address 3fff:ff::50/64
!
interface eth3
 description to transit (AS 65030, backup path)
 ip address 100.64.35.2/30
 ipv6 address 3fff:30:0:35::2/64
!
ip route 10.50.0.0/16 Null0
ipv6 route 3fff:50::/32 Null0
!
router bgp 65050
 bgp router-id 10.50.255.1
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 no bgp default ipv4-unicast
 neighbor 100.64.99.1 remote-as 65100
 neighbor 3fff:ff::1 remote-as 65100
 neighbor 100.64.35.1 remote-as 65030
 neighbor 3fff:30:0:35::1 remote-as 65030
 !
 address-family ipv4 unicast
  network 10.50.0.0/16
  neighbor 100.64.99.1 activate
  neighbor 100.64.35.1 activate
  neighbor 100.64.35.1 route-map PREPEND-TO-TRANSIT out
 exit-address-family
 !
 address-family ipv6 unicast
  network 3fff:50::/32
  neighbor 3fff:ff::1 activate
  neighbor 3fff:30:0:35::1 activate
  neighbor 3fff:30:0:35::1 route-map PREPEND-TO-TRANSIT out
 exit-address-family
!
route-map PREPEND-TO-TRANSIT permit 10
 set as-path prepend 65050 65050 65050
!
