frr defaults traditional
hostname route-server
service integrated-vtysh-config
!
interface eth1
 description IXP peering LAN
 ip address 100.64.99.1/24
 ipv6 address 3fff:ff::1/64
!
router bgp 65100
 bgp router-id 100.64.99.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 100.64.99.10 remote-as 65010
 neighbor 3fff:ff::10 remote-as 65010
 neighbor 100.64.99.20 remote-as 65020
 neighbor 3fff:ff::20 remote-as 65020
 neighbor 100.64.99.40 remote-as 65040
 neighbor 3fff:ff::40 remote-as 65040
 neighbor 100.64.99.50 remote-as 65050
 neighbor 3fff:ff::50 remote-as 65050
 neighbor 100.64.99.100 remote-as 65001
 neighbor 3fff:ff::100 remote-as 65001
 !
 address-family ipv4 unicast
  neighbor 100.64.99.10 activate
  neighbor 100.64.99.10 route-server-client
  neighbor 100.64.99.20 activate
  neighbor 100.64.99.20 route-server-client
  neighbor 100.64.99.40 activate
  neighbor 100.64.99.40 route-server-client
  neighbor 100.64.99.50 activate
  neighbor 100.64.99.50 route-server-client
  neighbor 100.64.99.100 activate
  neighbor 100.64.99.100 route-server-client
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 3fff:ff::10 activate
  neighbor 3fff:ff::10 route-server-client
  neighbor 3fff:ff::20 activate
  neighbor 3fff:ff::20 route-server-client
  neighbor 3fff:ff::40 activate
  neighbor 3fff:ff::40 route-server-client
  neighbor 3fff:ff::50 activate
  neighbor 3fff:ff::50 route-server-client
  neighbor 3fff:ff::100 activate
  neighbor 3fff:ff::100 route-server-client
 exit-address-family
!
